FROM node:18-alpine as builder

WORKDIR /app

COPY ["package.json", "package-lock.json", "./"]

RUN npm install

ARG VITE_SERVER_URL
ARG VITE_KAKAO_KEY
ARG VITE_KAKAO_JS_KEY
ARG VITE_MY_URL

ENV VITE_SERVER_URL ${VITE_SERVER_URL}
ENV VITE_KAKAO_KEY ${VITE_KAKAO_KEY}
ENV VITE_KAKAO_JS_KEY ${VITE_KAKAO_JS_KEY}
ENV VITE_MY_URL ${VITE_MY_URL}

COPY . .

RUN npm run build 

FROM nginx:1.25-alpine

COPY --from=builder /app/dist/ /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
